#!/bin/bash

SOURCE_FILE=$1
DESTINATION_FOLDER=$2

PHRASE=`cat $SOURCE_FILE`
CLASS_NAME=`basename $SOURCE_FILE`
CLASS_NAME="${CLASS_NAME%.speak}"


INCLUDE_GUARD=$CLASS_NAME"_H"
DECLARATION_FILE_NAME=$CLASS_NAME".h"
DEFINITION_FILE_NAME=$CLASS_NAME".cpp"
INCLUDE_GUARD=$CLASS_NAME"_H"


mkdir -p $DESTINATION_FOLDER

cat << EOF > $DESTINATION_FOLDER"/"$DECLARATION_FILE_NAME
#ifndef $INCLUDE_GUARD
#define $INCLUDE_GUARD

class $CLASS_NAME
{
public:
    void speak() const;
};
#endif /* $INCLUDE_GUARD */

EOF


cat << EOF > $DESTINATION_FOLDER"/"$DEFINITION_FILE_NAME
#include "$DECLARATION_FILE_NAME"
#include <stdio.h>
void $CLASS_NAME::speak() const
{
    printf("$PHRASE\n");
};

EOF

echo $DESTINATION_FOLDER"/"$DEFINITION_FILE_NAME
